/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDashboardConfigRouteImport } from './routes/api/dashboard-config'
import { Route as ApiWebrtcSignalRouteImport } from './routes/api/webrtc/signal'
import { Route as ApiWebrtcEventsRouteImport } from './routes/api/webrtc/events'
import { Route as ApiWebrtcChatRouteImport } from './routes/api/webrtc/chat'
import { Route as ApiWebrtcAssistantRouteImport } from './routes/api/webrtc/assistant'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardConfigRoute = ApiDashboardConfigRouteImport.update({
  id: '/api/dashboard-config',
  path: '/api/dashboard-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebrtcSignalRoute = ApiWebrtcSignalRouteImport.update({
  id: '/api/webrtc/signal',
  path: '/api/webrtc/signal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebrtcEventsRoute = ApiWebrtcEventsRouteImport.update({
  id: '/api/webrtc/events',
  path: '/api/webrtc/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebrtcChatRoute = ApiWebrtcChatRouteImport.update({
  id: '/api/webrtc/chat',
  path: '/api/webrtc/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebrtcAssistantRoute = ApiWebrtcAssistantRouteImport.update({
  id: '/api/webrtc/assistant',
  path: '/api/webrtc/assistant',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/dashboard-config': typeof ApiDashboardConfigRoute
  '/api/webrtc/assistant': typeof ApiWebrtcAssistantRoute
  '/api/webrtc/chat': typeof ApiWebrtcChatRoute
  '/api/webrtc/events': typeof ApiWebrtcEventsRoute
  '/api/webrtc/signal': typeof ApiWebrtcSignalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/dashboard-config': typeof ApiDashboardConfigRoute
  '/api/webrtc/assistant': typeof ApiWebrtcAssistantRoute
  '/api/webrtc/chat': typeof ApiWebrtcChatRoute
  '/api/webrtc/events': typeof ApiWebrtcEventsRoute
  '/api/webrtc/signal': typeof ApiWebrtcSignalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/dashboard-config': typeof ApiDashboardConfigRoute
  '/api/webrtc/assistant': typeof ApiWebrtcAssistantRoute
  '/api/webrtc/chat': typeof ApiWebrtcChatRoute
  '/api/webrtc/events': typeof ApiWebrtcEventsRoute
  '/api/webrtc/signal': typeof ApiWebrtcSignalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/dashboard-config'
    | '/api/webrtc/assistant'
    | '/api/webrtc/chat'
    | '/api/webrtc/events'
    | '/api/webrtc/signal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/dashboard-config'
    | '/api/webrtc/assistant'
    | '/api/webrtc/chat'
    | '/api/webrtc/events'
    | '/api/webrtc/signal'
  id:
    | '__root__'
    | '/'
    | '/api/dashboard-config'
    | '/api/webrtc/assistant'
    | '/api/webrtc/chat'
    | '/api/webrtc/events'
    | '/api/webrtc/signal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDashboardConfigRoute: typeof ApiDashboardConfigRoute
  ApiWebrtcAssistantRoute: typeof ApiWebrtcAssistantRoute
  ApiWebrtcChatRoute: typeof ApiWebrtcChatRoute
  ApiWebrtcEventsRoute: typeof ApiWebrtcEventsRoute
  ApiWebrtcSignalRoute: typeof ApiWebrtcSignalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard-config': {
      id: '/api/dashboard-config'
      path: '/api/dashboard-config'
      fullPath: '/api/dashboard-config'
      preLoaderRoute: typeof ApiDashboardConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webrtc/signal': {
      id: '/api/webrtc/signal'
      path: '/api/webrtc/signal'
      fullPath: '/api/webrtc/signal'
      preLoaderRoute: typeof ApiWebrtcSignalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webrtc/events': {
      id: '/api/webrtc/events'
      path: '/api/webrtc/events'
      fullPath: '/api/webrtc/events'
      preLoaderRoute: typeof ApiWebrtcEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webrtc/chat': {
      id: '/api/webrtc/chat'
      path: '/api/webrtc/chat'
      fullPath: '/api/webrtc/chat'
      preLoaderRoute: typeof ApiWebrtcChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webrtc/assistant': {
      id: '/api/webrtc/assistant'
      path: '/api/webrtc/assistant'
      fullPath: '/api/webrtc/assistant'
      preLoaderRoute: typeof ApiWebrtcAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDashboardConfigRoute: ApiDashboardConfigRoute,
  ApiWebrtcAssistantRoute: ApiWebrtcAssistantRoute,
  ApiWebrtcChatRoute: ApiWebrtcChatRoute,
  ApiWebrtcEventsRoute: ApiWebrtcEventsRoute,
  ApiWebrtcSignalRoute: ApiWebrtcSignalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
